### ISSUE TITLE
Create a User Model

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#1]
Inside the 'lib\models' folder, create a new file called 'User.dart'.

The path of the file should be: lib\models\User.dart

The user model should include the following variables:

1. First Name
2. Last Name
3. Email
4. Password
5. Difficulty Level

**Comment by jaziba-ux** [comment]
can i have this assigned to me

**Comment by markhallak** [comment]
Sure!

**Comment by alastairrmcneill** [comment]
Heya @markhallak this seems like a quick and easy one to get started on to help me test out learning to fork and do PRs. I know it has already been assigned, but is it possible to assign this to me or are there other models that need made currently that I could work on to test out the process?

**Comment by markhallak** [comment]
Hey @jaziba-ux 

What is the progress regarding this issue?

Do you prefer if you work with @alastairrmcneill on this issue (if he is down), or stop working on this issue and let him work on it instead?

**Comment by alastairrmcneill** [comment]
Heya @markhallak any update on this? I would be keen to get started on learning how to do the workflow and this will take a few minutes of actual coding so is a great learning opp.

**Comment by markhallak** [comment]
Hey @alastairrmcneill 

Unfortunately, I didn't receive any message from @jaziba-ux .

Therefore, I will assign this task to you.

**Comment by jaziba-ux** [comment]
hey i just got the chance to open github, sorry for the late reply, if its not too late I would like to work with @alastairrmcnell

**Comment by markhallak** [comment]
Hey! No worries.

I don't mind at all. If @alastairrmcneill doesn't mind working with you, I will assign you.

**Comment by alastairrmcneill** [comment]
Ah sorry @jaziba-ux! I just saw this as I came to push my work to the main repo. :( Sorry we didn't get the chance to collaborated on this but I think there is a decent change I got the process of forking, committing, pushing and creating pull requests wrong so there is probably a chance for us to collab in the future!

**Comment by alastairrmcneill** [comment]
Heya @markhallak I'm not sure how I link the pull request to this issue, so I thought I'd tag you in both...

**Comment by markhallak** [comment]
Hey @alastairrmcneill 

You got everything right! Thanks for the help! I have requested some changes before merging.

**Comment by markhallak** [comment]
@alastairrmcneill Thanks for contributing!
