### ISSUE TITLE
Add a Side Menu

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#10]
After issue #5 is closed.

Add a hamburger icon to the topbar to the left which toggles a side menu.

The side menu should contain the following items:
- Home Page with a home icon
- Leaderboards with a random icon (for now)

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.

**Comment by abhinav1912** [comment]
Just curious, why are we using a side bar/menu for this? For mobile devices, a tab bar is usually used for this navigation.

**Comment by markhallak** [comment]
Come to think of it. We should check how many pages there will be exactly and maybe go with a bottom navigation bar. It might be a better design choice.

I will close this issue for now. If you want to give any suggestions, please do on our discord.

Thanks!
