### ISSUE TITLE
Add a Rounded Profile Picture widget to the Top Bar

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#11]
After issue #5 is closed.

Add a rounded profile picture widget in the top bar to the right.

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.

**Comment by hayelomt** [comment]
i can take on this issue

**Comment by markhallak** [comment]
Issue #5 is not closed yet but you can create the profile picture widget as a separate component and add it to the components folder.

You can test it on a temporary page. Make sure you don't include the temporary page in the PR.

**Comment by markhallak** [comment]
Thank you for contributing!
