### ISSUE TITLE
Build a Popup Window to ask the user about their mood

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#17]
The popup window should include the following:
- The following text: "How are you feeling right now?"
- A slider with 5 values: Awful (1), Not Good (2), Fine (3), Very Good (4), Great (5)
- A button to close the popup window (the functionality of the button should be in a separate function since background work will be added later)

Nice to have:
- The slider would change color depending on the value selected
- Represent the values with emojis instead of text
- The emojis animate a little once the selected value changes.

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.
- Place the popup window in the 'components' folder.
- The code should include comments where necessary
- Set the maximum value of the slider to 5 and the step to 1

**Comment by vikas-shrma** [comment]
@markhallak add it to me or any other High - priority issue

**Comment by markhallak** [comment]
Hey @vikas-shrma. I don't think there will be a high-priority issue soon (for at least 3 days since I have to do some work before creating a new high-priority issue). So you're welcome to take this issue.

**Comment by vikas-shrma** [comment]
Okay. Do we have any mock-up or reference for this dialog.Sent from Android deviceOn 26-Feb-2023 5:30 pm, markhallak ***@***.***> wrote:
Hey @vikas-shrma. I don't think there will be a high-priority issue soon (for at least 3 days since I have to do some work before creating a new high-priority issue). So you're welcome to take this issue.

**Comment by markhallak** [comment]
Unfortunately, no. For now, we are just building the components with no regard for the design.

**Comment by vikas-shrma** [comment]
Ohk. I will create with dummy design

**Comment by Lovish-Singla** [comment]
Can i also pick this up?

**Comment by markhallak** [comment]
Thanks, @Lovish-Singla! Appreciated it!
