### ISSUE TITLE
Build a Popup Window to show the user affirmations

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#19]
The popup window should include the following:
- Text showing the affirmation
- Close button

Notes:
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.
- Place the popup window in the 'components' folder

**Comment by alastairrmcneill** [comment]
Heya @markhallak please assign this one to me. 

Just to confirm, we aren't designing this to any mock ups or anything, just base components? 

What do you mean by affirmation?

**Comment by alastairrmcneill** [comment]
Also do we want this to be platform specific? So showing a Cupertino dialog on iOS but a regular dialog on Android?

**Comment by markhallak** [comment]
Hey @alastairrmcneill 

1. Just build the base components with a basic design. Nothing fancy.
2. Affirmation is just an expression that makes some feels good such as "You are a great human being". You are not required to come up with "affirmations". You are only required to build the base components. Keep in mind that we want to get the "affirmation" from a database. So we might need to pass some data to the modal by the constructor.
3. It doesn't have to be platform specific. It is better if we keep the design consistent across all platforms.

**Comment by alastairrmcneill** [comment]
@markhallak sure thing, thanks! 

Will the affirmations just be text or do we have an affirmation model with text, image etc.? Just trying to decide what to set as the parameter for the constructor to the dialog

**Comment by markhallak** [comment]
It will be text only.

**Comment by alastairrmcneill** [comment]
@markhallak awesome, sounds good. Please assign it to me and I'll get to it this afternoon.

**Comment by markhallak** [comment]
Done
