### ISSUE TITLE
Build a Sign Up Page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#2]
The sign-up should include the following:
- First Name Input Bar
- Last Name Input Bar
- Email Input Bar
- Password Input Bar
- Confirmation Password Input Bar
- Sign up button

Leave some space after each input bar to show errors.

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.
- Place the sign up page in the 'pages' folder.

**Comment by bishnoitejal21** [comment]
Do you have a design or a theme in mind for this? Or do you want just a basic structure to be made for this?

**Comment by markhallak** [comment]
We don't have a design or a theme yet. We are still working on it.

For now, let's have a basic structure for the sign-up page.

Let me know if you want to work on this issue.

**Comment by bishnoitejal21** [comment]
Okay. Can you assign this to me?

**Comment by markhallak** [comment]
Sure. Please make sure you have updated your local project as I have made some changes to the file structure.

**Comment by markhallak** [comment]
Hey @bishnoitejal21 

Any updates? Are you facing any problems?

We are ready to assist.

**Comment by bishnoitejal21** [comment]
Really sorry for not updating anything yet. I got really busy due to my exams. 
And No, I haven't faced any issue yet.

**Comment by markhallak** [comment]
Hey @bishnoitejal21 

Any updates? Are you facing any problems?

**Comment by bishnoitejal21** [comment]
I am halfway through the issue. No problems yet

**Comment by markhallak** [comment]
@bishnoitejal21 Any progress?

**Comment by lydecker23** [comment]
I am willing to help if possible

**Comment by markhallak** [comment]
@lydecker23 Thanks for being interested in working on this issue.

@bishnoitejal21 do you mind working with @lydecker23 on this issue? I think it might be better so we can get this issue closed as soon as possible.

**Comment by aldorithms** [comment]
I have a sign up page I've already made that I can reuse if you're interested.

**Comment by markhallak** [comment]
@aldorithms do you mind sharing a screenshot?

**Comment by aldorithms** [comment]
> @aldorithms do you mind sharing a screenshot?

Certainly. This was done in React, but most of it can just be ported over. I can adjust the stylization & input boxes based on your needs.
![account](https://user-images.githubusercontent.com/99375833/221697285-b453e183-f56a-4342-9938-00fa34815f33.png)

**Comment by markhallak** [comment]
@aldorithms It looks good. Let's wait for @bishnoitejal21.

If he doesn't respond, do you mind working with @lydecker23?

**Comment by aldorithms** [comment]
@markhallak perfectly acceptable.

**Comment by markhallak** [comment]
It seems like @bishnoitejal21 is not active anymore.

@aldorithms @lydecker23 Please work together on developing the signup page if you are still interested.

We have a design ready for the signup page. Refer to it.
https://www.figma.com/file/JVVwblJQLnaDEc04tZTY8G/Untitled?node-id=0%3A1&t=TXGK8JEaF29W7ABG-1

Thanks!

**Comment by lydecker23** [comment]
Yes I am still interested

**Comment by bishnoitejal21** [comment]
I was having some issue with GitHub and thus I lost my code 
Sorry about not responding

**Comment by aldorithms** [comment]
> It seems like @bishnoitejal21 is not active anymore.
> 
> @aldorithms @lydecker23 Please work together on developing the signup page if you are still interested.
> 
> We have a design ready for the signup page. Refer to it. https://www.figma.com/file/JVVwblJQLnaDEc04tZTY8G/Untitled?node-id=0%3A1&t=TXGK8JEaF29W7ABG-1
> 
> Thanks!

I'll work on it as soon as I can.

**Comment by markhallak** [comment]
> I was having some issue with GitHub and thus I lost my code Sorry about not responding

No worries. Do you mind if they work on the issue instead?

**Comment by bishnoitejal21** [comment]
It's fine. They can work on the issue. I have an exam coming up so won't be able to devote my time.

**Comment by markhallak** [comment]
> It's fine. They can work on the issue. I have an exam coming up so won't be able to devote my time.

Sounds good. All the best on your exam!

**Comment by lydecker23** [comment]
@aldorithms are you available to collaborate?

**Comment by markhallak** [comment]
@lydecker23 did you get any response from @aldorithms?

**Comment by lydecker23** [comment]
@markhallak no I did not. I have been working the issue however and I am near completion.

**Comment by markhallak** [comment]
@lydecker23 whoever is done can create a PR for this issue. Hopefully, pairing with other developers would be better in the future.

**Comment by markhallak** [comment]
Thanks, @lydecker23!
