### ISSUE TITLE
Add a "Create an Account" text in the login page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#23]
Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.

**Comment by alastairrmcneill** [comment]
Heya @markhallak I can take this one on. 

Quick question: 
Do you want the text to be a button that takes you to the AccountCreation page?

**Comment by markhallak** [comment]
@alastairrmcneill 

Yes. I want the text to work as a button but appear as normal text. I think using a gesture detector widget might help us with achieving similar behavior.
