### ISSUE TITLE
Create a Customized TextField

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#25]
Create a base TextField that can be customized upon initialization.

For example, we have a base TextField with a color attribute that is red.
Usage 1: We should be able to change its color
Usage 2: We should be able to change the value of its 'keyboardType' attribute and such.

**Comment by notbrood** [comment]
Can you assign this to me, I have a code snippet on it which we can modify for this issue?
@markhallak

**Comment by markhallak** [comment]
Sure

**Comment by notbrood** [comment]
Hey mark! I have created a pull request for this issue, I have added the textfield with a bunch of attributes, if you want anything to change, please let me know.
