### ISSUE TITLE
Build the Login Page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#3]
The login page should include the following:
- Email input bar
- Password input bar
- Reset password button
- Login button

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.
- Place the login page in the 'pages' folder.

**Comment by Prince-1110** [comment]
Assign this task to me.

**Comment by markhallak** [comment]
Done. Make sure you work on the "dev" branch. After you are done, create a PR to merge into the "dev" branch.

**Comment by markhallak** [comment]
Also, create a folder called "Models" and the model to the folder.

**Comment by Prince-1110** [comment]
Only static page is required ?

**Comment by markhallak** [comment]
Sorry, I commented on the wrong issue.

Yes, the page should be static for now.

**Comment by markhallak** [comment]
I have changed the file structure. I have manually added the folders and sample files.

Please update your local project accordingly.

Sorry about that.

**Comment by markhallak** [comment]
Hey @Prince-1110

Any updates? Are you facing any problems?

We are ready to assist.

**Comment by Prince-1110** [comment]
No, I haven't faced any issue yet and thanks for your concern.

**Comment by markhallak** [comment]
Hey @Prince-1110 

Any updates? Are you facing any problems?

**Comment by Prince-1110** [comment]
Completed and pull request is also raised.

**Comment by markhallak** [comment]
Thank you a lot! I will take a look at it now.

**Comment by hayelomt** [comment]
i can work on this issue

**Comment by markhallak** [comment]
Assigned

**Comment by markhallak** [comment]
@titanht Thanks for contributing!

**Comment by hayelomt** [comment]
No problem
