### ISSUE TITLE
Create a Customized Button

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#31]
Create a base Button that can be customized upon initialization.

For example, we have a base TextField with a color attribute that is red.
We should be able to change its color and any other attribute, especially its text.

This issue is similar to #25

Notes:
- Update your local project before working on the issue
- File names should use the `CamelCase` convention
- Variable names should use the `lowerCamelCase` convention
- Frequently used components should be placed inside the `lib/components` folder
- Pages should be placed inside the `lib/pages` folder
- Format your code before creating a PR
- Remove any unused imports

**Comment by notbrood** [comment]
Can I work on this?

**Comment by markhallak** [comment]
Sure

**Comment by notbrood** [comment]
Hey @markhallak, I have finished working on this and created a PR, let me know if I have to change anything!
