### ISSUE TITLE
Update the Login Page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#32]
![Welcome](https://user-images.githubusercontent.com/65905058/222906884-1bd60d78-69d9-43b0-811f-fe2d0615da0c.png)

This is the design for the login page. Update the login page, which was built before, to be identical to the above picture. No functionality is needed.

For the email and password input fields, use the `CustomTextField` component (you can find it inside the `lib/components` folder).

Don't add the "Continue with Apple" button.

Notes:
- Update your local project before working on the issue
- File names should use the `CamelCase` convention
- Variable names should use the `lowerCamelCase` convention
- Frequently used components should be placed inside the `lib/components` folder
- Pages should be placed inside the `lib/pages` folder
- Format your code before creating a PR
- Remove any unused imports

**Comment by hayelomt** [comment]
i can take this issue

**Comment by markhallak** [comment]
Assigned!
