### ISSUE TITLE
Create a Search Field Component with Suggestions

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#33]
Use the `searchfield` [library](https://pub.dev/packages/searchfield) to build this component.

We need this component to change the styling of the original widget only. The way we initialize the widget should stay the same.

Notes:
- Update your local project before working on the issue
- File names should use the `CamelCase` convention
- Variable names should use the `lowerCamelCase` convention
- Frequently used components should be placed inside the `lib/components` folder
- Pages should be placed inside the `lib/pages` folder
- Format your code before creating a PR
- Remove any unused imports

**Comment by notbrood** [comment]
Hey mark can I start working on this?

**Comment by markhallak** [comment]
Yeah!

**Comment by notbrood** [comment]
Hey @markhallak, I have finished working on this and created a PR, let me know if I have to change anything!

**Comment by markhallak** [comment]
@notbrood Modified it. Let me know if you are still interested.

**Comment by notbrood** [comment]
i'm done for today mark, it's 5am, I'll unassign myself, if anyone else wants to work on it they can, if it's unassigned tommorow, I'll take it.

**Comment by markhallak** [comment]
Okay then. Sorry again.

**Comment by notbrood** [comment]
Itsokay man, no worries! mistakes happen, and I appreciate you taking the time to apologize.

**Comment by notbrood** [comment]
Hey mark! is anyone working on this or can I contribute to this.

**Comment by markhallak** [comment]
No one is working on it. I will assign you. Thanks for checking!

**Comment by notbrood** [comment]
Hey @markhallak, I have finished working on this and created a PR in #45, let me know if I have to change anything!

**Comment by markhallak** [comment]
Thanks!
