### ISSUE TITLE
Connect the app to a Firebase DB

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#4]

**Comment by ShivamMenda** [comment]
@markhallak I would like to take this up and we can set it up after a substantial amount of UI work is done and discuss the DB structure in the meeting we'll be having in the coming weeks.

**Comment by markhallak** [comment]
Agree! Let's work on it together.

**Comment by ShivamMenda** [comment]
@markhallak Done!

**Comment by ShivamMenda** [comment]
Hey @markhallak Has this issue been completed? I'm so sorry I'm offline due to exams :(

**Comment by markhallak** [comment]
Hey @ShivamMenda.

Yes, it is completed. I forgot to tell you, but I had to do it fast so I can test sending push notifications by FCM.

Maybe, we can work on issue #18 but I think you have to replicate the database/firebase project since it is not a good idea to share the firebase credentials file online. I am not sure if there is any other way to do it. Maybe we can add authentication.

No worries. This is an open-source project. You don't have to dedicate your time to it.

**Comment by ShivamMenda** [comment]
@markhallak No problem will work on the Notifications with you as soon as exams are done. You can add me as a collaborator on firebase. Here's my email: shivammenda2002@gmail.com

**Comment by markhallak** [comment]
@ShivamMenda I have added you as an editor. You should be able to access everything.

**Comment by ShivamMenda** [comment]
@markhallak I've got access to firebase. Will work on FCM with you 👍
