### ISSUE TITLE
Build the Home Page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#5]
The home page should have the following:
- A red Topbar
- The name of the app "AnxietyGo" in the middle

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.
- Place the home page in the 'pages' folder.

**Comment by Aspheles** [comment]
Still pretty new to flutter, could I try to pick this up?

**Comment by markhallak** [comment]
Sure. You can pair up with someone to work on it or you can ask for help in the help channel on discord if you face any problems.

**Comment by Aspheles** [comment]
I will try to pick it up alone if it gets tough will ask some help later

**Comment by markhallak** [comment]
Hey @Aspheles 

How is it going? Are you facing any problems?

I am ready to assist.

**Comment by DevAgarwal2** [comment]
hey i will like to work in this issue I am noctus

**Comment by DevAgarwal2** [comment]
bro can you pls give the access so I can pull request

**Comment by markhallak** [comment]
Sure! Sorry about the delay.

**Comment by markhallak** [comment]
Hey @Zephyr993 

Any updates? Are you facing any problems?

**Comment by Lovish-Singla** [comment]
Could I also pick-up this issue?

**Comment by markhallak** [comment]
Sure. It seems like @Zephyr993 is inactive.

**Comment by markhallak** [comment]
@Lovish-Singla Thanks for the help!
