### ISSUE TITLE
Create a Challenge Model

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#6]
Inside the 'lib\models' folder, create a new file called 'Challenge.dart'.

The path of the file should be: lib\models\Challenge.dart

It should include the following variables:
- Name
- Description
- Difficulty
- Category
- Thumbnail

Note: All of the variables are strings except for the difficulty. The thumbnail will store a reference to a picture that is uploaded to firebase.

**Comment by abhinav1912** [comment]
I’d like to pick this task
