### ISSUE TITLE
Add a Carousel Slider in the Home Page

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#7]
After issue #6 is closed.

Use the following package to add a Carousel Slider in the home page:
https://pub.dev/packages/carousel_slider

The carousel slider needs to be horizontal and it consists of cards. Each card will show the thumbnail and the name of the challenge.

Notes:
- Don't add any functionality.
- Each component should be in a separate file located in the 'components' folder in the 'lib' folder.

**Comment by vikas-shrma** [comment]
i can take this task

**Comment by markhallak** [comment]
Issue #6 is not closed yet but you can create the carousel slider as a separate component and add it to the components folder.

You can test it on a temporary page. Make sure you don't include the temporary page in the PR.
